# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'HNKWordLookup' do

pod 'HNKWordLookup', '~> 0.1'

end

target 'HNKWordLookupTests' do

end

link_with 'HNKWordLookup', 'HNKWordLookupTests'
